### ISSUE TITLE
将一个用了flexiable库适配的html作为iframe嵌入到另一个也用了该库的html中页面会混乱

### ISSUE THREAD

**Issue by balsampearshen** [amfe/article#43]
将一个用了flexiable库适配的html作为iframe嵌入到另一个也用了该库的html中，则页面会混乱字体大小也会很奇怪

**Comment by riotkkwok** [comment]
原因应该是iframe不支持viewport伸缩吧

**Comment by songsiqi** [comment]
是缩放 viewport 引起的。单个页面没事，但是在页面中使用了 iframe、canvas 会出现问题。可以先手动添加

```
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no">
```

防止缩放 viewport。

缩放 viewport 仅仅是为了实现 1px 的细线效果。其实从 iOS 8 开始，就支持 0.5px 的边框了。只要通过特性判断，让支持 0.5px 的 iOS 设备显示细线，不支持的降级为粗线即可，例如：

``` css
.demo {
  border: 1px solid #ddd;
}
.hairlines .demo {
  border: 0.5px solid #ddd;
}
```

推荐新工具 [postcss-adaptive](https://www.npmjs.com/package/postcss-adaptive)。

后续可以考虑改成这种方案。
