### ISSUE TITLE
关于font-size和line-height的问题

### ISSUE THREAD

**Issue by flyer153** [amfe/article#46]
有一个问题，我在iphone4和5的html中data-dpr为2时，font-size: 64px;
在iphone6的html中data-dpr为2，font-size: 75px;
在iphone6p的html中data-dpr为3，font-size: 124.5px;

我发现font-size用px的话，会有问题，在各手机下会出现字体大小不一样的情况，而字体用rem就没问题。

看到说推荐字体用px，为什么要用px呢？我表示不解。
另外如果字体用px，line-height怎么用呢？我现在字体用px的话line-height用的是rem。

**Comment by airen** [comment]
对于`line-height`而言，不管在何处，都不建议给`line-height`的值添加显式的单位，个人更建议这样的使用方式：

``` css
body {
        line-height: 1.625;
}
```

而不使用

``` css
body {
       line-height: 28px;
      /*或者*/
      line-height: 1em;
     /*或者*/
      line-height: 1rem; 
}
```
